[platformio]
default_envs = rpipico2w

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 768k
monitor_speed = 115200
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    -DHANKINATOR_ENABLE_WIFI_UPDATER=1
lib_deps =
    olikraus/U8g2
	adafruit/Adafruit NeoPixel
	teemuatlut/TMCStepper@^0.7.3

[env:rpipico2w]
board = rpipico2w

[env:rpipicow]
board = rpipicow
