[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 768k
monitor_speed = 115200
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    -DHANKINATOR_ENABLE_WIFI_UPDATER=0
lib_deps =
    olikraus/U8g2
	adafruit/Adafruit NeoPixel
	teemuatlut/TMCStepper@^0.7.3
